import os

TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
CHAT_ID = os.getenv("CHAT_ID")

CAPITAL = 200
MAX_LEVERAGE = 25

MAX_SIGNALS_PER_DAY = 20
MAX_HIGH_PER_DAY = 4

TIMEZONE = "Europe/Rome"
START_HOUR = 0
END_HOUR = 23

# Bybit Linear USDT Perpetual
SYMBOLS = [
    "BTC/USDT:USDT",
    "ETH/USDT:USDT",
    "SOL/USDT:USDT",
    "BNB/USDT:USDT",
    "XRP/USDT:USDT",
]
